#!/usr/bin/env php
<?php

require_once __DIR__.'/../vendor/autoload.php';

use ProjektGopher\FFMpegTween\Enums\Ease as AvailableEasings;
use ProjektGopher\FFMpegTween\Ease;

echo 'starting... (fail fast)'.PHP_EOL;

$time = "X/H";

foreach (AvailableEasings::cases() as $ease) {
    echo "Generating snapshot for {$ease->value} easing...".PHP_EOL;
    $easeMultiplier = Ease::{$ease->value}($time);
    
    $input = "-f lavfi -i \"color=c=black:s=256x256:d=1\"";
    $filter = "-vf \"geq=if(eq(round(H*({$easeMultiplier}))\,H-Y)\,128\,0):128:128\"";
    $out = "-frames:v 1 -update 1 tests/Snapshots/{$ease->value}.png";
    $redirect = '2>&1'; // redirect stderr to stdout

    $cmd = "ffmpeg -y {$input} {$filter} {$out} {$redirect}";
    
    (array) $output = [];
    (int) $code = 0;
    exec($cmd, $output, $code);

    if ($code !== 0) {
        echo PHP_EOL;
        echo "Failed to generate snapshot for {$ease->value} easing.".PHP_EOL;
        echo "Output: ".PHP_EOL;
        echo implode(PHP_EOL, $output).PHP_EOL;
        exit(1);
    }
}
